-- PRAVILNIK
-- O SPECIJALIZACIJAMA I UŽIM SPECIJALIZACIJAMA ZDRAVSTVENIH RADNIKA I ZDRAVSTVENIH SARADNIKA
-- ("Sl. glasnik RS", br. 10/2013, 91/2013, 113/2013, 109/2014 i 53/2018)
INSERT INTO specializations (id, name) VALUES
(1, 'Doktor medicine - bez specijalizacije'),
(2, 'Interna medicina'),
(3, 'Internistička onkologija'),
(4, 'Infektologija'),
(5, 'Pedijatrija'),
(6, 'Neurologija'),
(7, 'Psihijatrija'),
(8, 'Dečja neurologija'),
(9, 'Dečja i adolescentna psihijatrija'),
(10, 'Ginekologija i akušerstvo'),
(11, 'Opšta hirurgija'),
(12, 'Abdominalna hirurgija'),
(13, 'Vaskularna hirurgija'),
(14, 'Grudna hirurgija'),
(15, 'Ortopedska hirurgija i traumatologija'),
(16, 'Dečja hirurgija'),
(17, 'Neurohirurgija'),
(18, 'Plastična, rekonstruktivna i estetska hirurgija'),
(19, 'Maksilofacijalna hirurgija'),
(20, 'Urologija'),
(21, 'Kardiohirurgija'),
(22, 'Urgentna medicina'),
(23, 'Anesteziologija, reanimatologija i intenzivna terapija'),
(24, 'Otorinolaringologija'),
(25, 'Oftalmologija'),
(26, 'Dermatovenerologija'),
(27, 'Fizikalna medicina i rehabilitacija'),
(28, 'Opšta medicina'),
(29, 'Medicina rada'),
(30, 'Radiologija'),
(31, 'Radijaciona onkologija'),
(32, 'Nuklearna medicina'),
(33, 'Patologija'),
(34, 'Sudska medicina'),
(35, 'Medicinska mikrobiologija'),
(36, 'Klinička biohemija'),
(37, 'Klinička farmakologija'),
(38, 'Laboratorijska medicina'),
(39, 'Imunologija'),
(40, 'Higijena'),
(41, 'Epidemiologija'),
(42, 'Socijalna medicina'),
(43, 'Sportska medicina'),
(44, 'Transfuzijska medicina'),
(45, 'Vazduhoplovna medicina'),
(46, 'Medicinska statistika i informatika'),
(47, 'Palijativna medicina'),
(48, 'Preventivna i dečja stomatologija'),
(49, 'Bolesti zuba i endodoncija'),
(50, 'Stomatološka protetika'),
(51, 'Parodontologija i oralna medicina'),
(52, 'Ortopedija vilica'),
(53, 'Oralna hirurgija'),
(54, 'Maksilofacijalna hirurgija'),
(55, 'Medicinska statistika i informatika');